### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MeetaliiPtl**
Updated README.md by seperating the lines for code blocks

### CODE REVIEW

**Comment by ankur0904** [comment]
@MeetaliiPtl Thanks for the PR
But we need a change.
Since the code block is present as ```code``` (\```code\```) but we don't want code block in this way, we want it in this way
```
code
```
\```
code
\```

**Review by ankur0904 — CHANGES_REQUESTED** [review]
Please make the suggested change

**Comment by MeetaliiPtl** [comment]
I've done the suggested changes.

**Review by ankur0904 — APPROVED** [review]

**Comment by ankur0904** [comment]
@MeetaliiPtl Thanks for the PR.

**Comment by ankur0904** [comment]
Fixed #6

**Pull request merged**
